dinov2:
  name: dinov2_vits14
  checkpoint: "dinov2/checkpoints/dinov2_vits14_pretrain.pth"

compvit:
  name: compvits14
  checkpoint: "toy_experiments/checkpoints_dino/2023-12-28-123358/best_performing.pt"

head:
  num_classes: 100
  # checkpoint: "toy_experiments/checkpoints_dino/2023-12-28-123358/best_performing_head.pt"
  # checkpoint: "toy_experiments/checkpoints_dino/2023-12-28-144328/best_performing_head.pt"
  checkpoint: ""


hyperparameters:
  lr: 1.0E-03
  min_lr: 1.0e-7
  warmup_lr_scale: 1.0e-4
  warmup_epochs: 10
  batch_size: 64
  test_batch_size: 32
  epochs: 300
  mixup_alpha: 0.8 
  accumulations: 1

device: cuda