teacher:
  name: dinov2_vits14
  checkpoint: "dinov2/checkpoints/dinov2_vits14_pretrain.pth"

student:
  name: compvits14

hyperparameters:
  lr: 1.0E-04
  min_lr: 1.0e-6
  warmup_lr_scale: 1.0e-3
  warmup_epochs: 20
  batch_size: 64
  epochs: 400
  mixup_alpha: 0.8 
  accumulations: 8

device: cuda:0
