teacher:
  name: dinov2_vits14
  checkpoint: "dinov2/checkpoints/dinov2_vits14_pretrain.pth"

student:
  name: compvits14
  # checkpoint: "dinov2/checkpoints/dinov2_vits14_pretrain.pth"
  decoder_checkpoint: "toy_experiments/checkpoints_dino/mae_2023-12-27-230758/best_performing_decoder.pt"
  checkpoint: "toy_experiments/checkpoints_dino/mae_2023-12-27-230758/best_performing.pt"

hyperparameters:
  lr: 1.0E-03
  min_lr: 1.0e-6
  warmup_lr_scale: 1.0e-3
  warmup_epochs: 20
  batch_size: 800
  epochs: 800
  mixup_alpha: 0.8 
  accumulations: 1

device: cuda:0
