dinov2:
  name: dinov2_vits14
  checkpoint: "dinov2/checkpoints/dinov2_vits14_pretrain.pth"

compvit:
  name: compvits14
  checkpoint: "toy_experiments/checkpoints_dino/mae_2023-12-23-154355/best_performing.pt"

head:
  num_classes: 100

hyperparameters:
  lr: 1.0E-03
  min_lr: 1.0e-5
  warmup_lr_scale: 1.0e-3
  warmup_epochs: 30
  batch_size: 64
  epochs: 200
  mixup_alpha: 0.8 
  accumulations: 8

device: cuda