teacher:
  name: dinov2_vits14
  checkpoint: "dinov2/checkpoints/dinov2_vits14_pretrain.pth"

student:
  name: compvits14
  # checkpoint: "dinov2/checkpoints/dinov2_vits14_pretrain.pth"
  # decoder_checkpoint: "toy_experiments/checkpoints_dino/mae_2023-12-27-230758/best_performing_decoder.pt"
  decoder_checkpoint: ""
  checkpoint: "toy_experiments/checkpoints_dino/mae_2024-01-09-030101/best_performing.pt"

hyperparameters:
  lr: 5.0E-03
  min_lr: 1.0e-8
  warmup_lr_scale: 1.0e-4
  warmup_epochs: 10
  batch_size: 256
  epochs: 200
  mixup_alpha: 0.8 
  accumulations: 2

device: cuda:0
data_loc: ""