dinov2:
  name: dinov2_vits14
  checkpoint: "dinov2/checkpoints/dinov2_vits14_pretrain.pth"

compvit:
  name: compvits14
  checkpoint: "dinov2/checkpoints/dinov2_vits14_pretrain.pth"

head:
  num_classes: 1000
  checkpoint: "checkpoints/2024-02-22-184952/best_performing_head.pt"


hyperparameters:
  lr: 0.5E-04
  min_lr: 1.0e-8
  warmup_lr_scale: 1.0e-4
  warmup_epochs: 10
  batch_size: 64
  test_batch_size: 32
  num_workers: 16
  epochs: 50
  mixup_alpha: 0.8 
  accumulations: 1
  in_memory: False

args:
  device: cuda:0
  data_dir_train: "/home/jajal/datasets/train_500_0.5_90.ffcv"
  data_dir_test: "/home/jajal/datasets/val_500_0.5_90.ffcv"
  precision: "bf16-mixed"