dinov2:
  name: dinov2_vits14
  checkpoint: "dinov2/checkpoints/dinov2_vits14_pretrain.pth"

compvit:
  name: compvits14
  checkpoint: "checkpoints/mae_2024-02-06-230335/best_performing.pth"

head:
  num_classes: 1000
  checkpoint: ""


hyperparameters:
  lr: 5.0E-05
  min_lr: 1.0e-8
  warmup_lr_scale: 1.0e-4
  warmup_epochs: 10
  batch_size: 256
  test_batch_size: 32
  num_workers: 16
  epochs: 60
  mixup_alpha: 0.8 
  accumulations: 1

args:
  device: cuda:0
  data_dir: "/scratch/gilbreth/pjajal/datasets/imagenet-1k"
  precision: "bf16-mixed"