teacher:
  name: dinov2_vits14
  checkpoint: "dinov2/checkpoints/dinov2_vits14_pretrain.pth"

student:
  name: compvits14
  # checkpoint: "dinov2/checkpoints/dinov2_vits14_pretrain.pth"
  checkpoint: "checkpoints/mae_2024-01-20-181842/best_performing.pth"
  decoder_checkpoint: ""

hyperparameters:
  lr: 5.0E-03
  min_lr: 1.0e-8
  warmup_lr_scale: 1.0e-4
  warmup_epochs: 10
  batch_size: 1024
  num_workers: 16
  epochs: 150
  mixup_alpha: 0.8 
  accumulations: 4

args:
  device: cuda:0
  data_dir: "/scratch/gilbreth/pjajal/datasets/imagenet-1k"
  precision: "bf16-mixed"