decoder:
  type: identity
  nhead: 16
  decoder_dim: 512
  mlp_ratio: 4
  dropout: 0.0
  activation: gelu
  layer_norm_eps: 1e-5
  norm_first: True
  num_layers: 8
loss: smooth
tradeoff: 0.1
use_logit: True
num_classes: 1000
# Path to the baseline head checkpoint. This is required when use_logit is True.
baseline_head_checkpt: "/scratch/gilbreth/pjajal/dinov2_vitl14_linear_head.pth" 