decoder:
  type: identity
  nhead: 16
  decoder_dim: 512
  mlp_ratio: 4
  dropout: 0.0
  activation: gelu
  layer_norm_eps: 1e-5
  norm_first: True
  num_layers: 8
loss: smooth
tradeoff: 1.0e-1
use_logit: True
num_classes: 1000